export const STRING = {
    se_connecter: 'Se connecter',
    sinscrire: "S’inscrire",
    adresse_email: 'Adresse Email',
    mot_de_passe: 'Mot de passe',
    mot_de_passe_oublié_q: 'Mot de passe oublié ?',
    pas_encore_de_compte: 'Pas encore de compte ?',
    connexion: 'Connexion',
    popupText: "Mot de passe oublié ? ",
    ok: 'Ok !',
    annuler: 'Annuler',
    mot_de_passe_oublié: 'Mot de passe oublié',
    enregistrer_le_nouveau_mot_de_passe: 'Enregistrer le nouveau mot de passe',
    nouveau_mot_de_passe: 'Nouveau mot de passe',
    confirmation_du_nouveau_mot_de_passe: 'Confirmation du nouveau mot de passe',
    nouveau_mot_de_passe_enregistré: 'Nouveau mot de passe enregistré !',
    je_me_connecte: 'Je me connecte',
    Profil: 'Profil',
    candidatures: 'Candidatures',
    missions: 'Missions',
    aide: 'Aide',
    headerText: "Trouve ton premier élève pour commencer l’aventure",
    Mesélèves: 'Mes élèves',
    Manote: 'Ma note',
    declare_a_mission: 'Déclarer une mission',
    declare_a_cours: 'Déclarer un cours',
    missions_available: 'Missions disponibles',
    see_everything: 'Tout voir',
    intéressé: 'Intéressé',
    refuser: 'Refuser',
    prendrerdv: 'Prendre RDV',
    contactcomptabilité: 'Contact comptabilité',
    unedemande: 'Une demande ?',
    Catégorie: 'Catégorie',
    taquestion: 'Ta question',
    envoyer: 'Envoyer',
    mesparrainages: 'Mes parrainages',
    ton_code: 'Ton code',
    felipe: 'FELIPE-26AI',
    copier: 'Copier',
    partager: 'Partager',
    tonprofilparrain: 'Ton profil parrain',
    prochainbadge: 'Prochain badge : Ambassad’Or',
    tuteurparrainé: 'Tuteur parrainé',
    heureseffectuées: "68/100 heures effectuées",
    superambassadeur: 'Super ambassadeur',
    Tonbadgeactuel: 'Ton badge actuel ',
    tefaisgagner: 'te fais gagner 3€/h de + ',
    enmoyenne: 'en moyenne sur chaque cours',
    cagnottetotale: 'Cagnotte totale',
    popupSubText: "Nous allons t’envoyer un mail de réinitialisation\ndu mot de passe."
}