export const STRING = {
    se_connecter: 'Se connecter',
    sinscrire: "S’inscrire",
    adresse_email: 'Adresse Email',
    mot_de_passe: 'Mot de passe',
    mot_de_passe_oublié_q: 'Mot de passe oublié ?',
    pas_encore_de_compte: 'Pas encore de compte ?',
    connexion: 'Connexion',
    popupText: "Mot de passe oublié ? Nous allons\nt’envoyer un mail de réinitialisation\ndu mot de passe.",
    ok: 'Ok !',
    annuler: 'Annuler',
    mot_de_passe_oublié: 'Mot de passe oublié',
    enregistrer_le_nouveau_mot_de_passe: 'Enregistrer le nouveau mot de passe',
    nouveau_mot_de_passe: 'Nouveau mot de passe',
    confirmation_du_nouveau_mot_de_passe: 'Confirmation du nouveau mot de passe',
    nouveau_mot_de_passe_enregistré: 'Nouveau mot de passe enregistré !',
    je_me_connecte: 'Je me connecte',
    compte: 'Compte',
    candidatures: 'Candidatures',
    missions: 'Missions',
    aide: 'Aide',
    headerText: "Texte de mise en avant de l’étape pour prochain badge",
    Mesélèves: 'Mes élèves',
    Manote: 'Ma note',
    declare_a_mission: 'Déclarer une mission',
    missions_available: 'Missions disponibles',
    see_everything: 'Tout voir',
    intéressé:'Intéressé',
    refuser: 'Refuser'
}